version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: sudo apt-get update && sudo apt-get install libnss3 
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI